### ISSUE TITLE
packaging for bower

### ISSUE THREAD

**Issue by thaiat** [bendrucker/angular-text-toggle#1]
Hi @bendrucker,

I'm using your module as a starting point to build an angular library that uses internally browserify and browerify-shim

Could you share the code that you used to build the release/angular-text-google.js file ?
I m struggling trying to figure out what is the strategy for excluding the dependcies from the published package, so don't end up twice in the consumer bundle

**Comment by bendrucker** [comment]
For sure — I created [publicist](https://github.com/bendrucker/publicist) to handle this.

**Comment by thaiat** [comment]
cool, but i see that angular code is not in your bower package, how did you achieve that ?

**Comment by bendrucker** [comment]
https://github.com/bendrucker/angular-text-toggle/blob/master/package.json#L50

There is never a `require('angular')` statement in the bundle after it's been transformed through b-shim.

**Comment by thaiat** [comment]
what about other require that are not globals or don't even have an export
for example ui-router?
how can you make sure the code does not end up in the bundle ?

**Comment by bendrucker** [comment]
Maybe https://github.com/bendrucker/angular-router-exception-handler will clarify. If you still don't get give me a little more detail and open something over at [bendrucker/discuss](https://github.com/bendrucker/discuss).
